language: c

os:
 - linux
 - osx

before_install:
 - env
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq automake libtool make python zlib1g-dev; fi
 # workaround for /usr/local/Library/ENV/4.3/sed: No such file or directory
 # http://stackoverflow.com/a/38471887
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew reinstall -s libtool; fi
 # https://github.com/travis-ci/travis-ci/issues/6307
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rvm get stable; fi

script:
 # abort on any command failure
 - set -e

 # build and install file
 - git clone --depth=100 git://github.com/file/file.git
 - cd file
 - test -z "$commit" || git checkout $commit
 - git log -1
 - autoreconf -f -i
 - case "$TRAVIS_OS_NAME" in osx) prefix=/usr/local;; linux) prefix=/usr;; esac
 - ./configure --prefix=$prefix
 - make -j4
   # remove system file package first
   # see https://github.com/file/file-tests/issues/3
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get remove -y libmagic1 file; fi
 - sudo make install
 - cd ..
 - which file
 - file --version

 # run file-tests
 - python update-db.py -m file/magic/Magdir
 - python fast-regression-test.py

# vim:ts=1:sw=1:et
